#!/bin/bash

# aliases
deck=$1
tmp_deck="/tmp/tmpdeck"

main() {
	# shuffle deck
	shuf $deck -o $tmp_deck
	mv $tmp_deck $deck

	# drill the items
	while read item; do
	    drill "$item"
	done < $deck
}

drill() {
	# set up variables
	IFS=';' read -a q <<< "$1"
	question="${q[0]}"
	answer="${q[1]}"

	# ask the question and get the quality
	echo -e  "\e[1mQUESTION:\e[0m $question"
	read -n 1 -s -r < /dev/tty
	echo -e "\e[1mANSWER:\e[0m   $answer\n"
}

main
